### ISSUE TITLE
感谢你的集成，我遇到麻烦了在我小米手机上，希望得到你的帮助~

### ISSUE THREAD

**Issue by Jetereting** [MiQt/X5WebView#1]
其他老手机都行，就是我的新手机还是调用系统的webkit 我打印了下异常
E/[image]: Load WebP Library Error...: libwebp.java - loadWepLibraryIfNeed()
E/Libstlport: Load Stlport Library Error...: libstlport.java
E/[image]: Load WebP Library Error...: libwebp.java - loadWepLibraryIfNeed()
E/TBSShell: TBS:initX5Core -- loadSucc: false; exception: java.lang.reflect.InvocationTargetException; cause: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.tencent.mm/app_tbs/core_share/libmttwebview.so" is 32-bit instead of 64-b
                at java.lang.Runtime.load(Runtime.java:332)
                at java.lang.System.load(System.java:1069)
                at com.tencent.smtt.webkit.ContextHolder.loadMttWebViewLib(Unknown Source)
                at com.tencent.smtt.webkit.ContextHolder.setContext(Unknown Source)
                at com.tencent.smtt.webkit.ContextHolder.setContext(Unknown Source)
                at java.lang.reflect.Method.invoke(Native Method)
                at com.tencent.tbs.x5core.X5CoreInit.setContextHolderParams(Unknown Source)
                at com.tencent.tbs.tbsshell.TBSShell.initX5CoreImpl(Unknown Source)
                at com.tencent.tbs.tbsshell.WebCoreProxy.canUseX5(Unknown Source)

                                                                     at java.lang.reflect.Method.invoke(Native Method)
                at com.tencent.smtt.sdk.bi.a(Unknown Source)
                at com.tencent.smtt.sdk.bh.a(Unknown Source)
                at com.tencent.smtt.sdk.f.run(Unknown Source)
E/X5CoreEngine: TBS:mCanUseX5 is false --> report
E/app:  onViewInitFinished is false
E/TbsCommonConfig: TBS:Config file is null, default values will be applied

**Comment by MiQt** [comment]
我更新了一下版本，再试试

**Comment by Jetereting** [comment]
爱死你了，可以了，谢谢谢谢谢谢

**Comment by hui453694187** [comment]
你好， 请问这个是如何解决的， 我在我的手机上也出现了这个问题 ，不适用你的库 ，如何解决的请问？
